MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/yzh_92/model/TransReID_res/pretrain_weights/resnet50-11ad3fa6.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [11, 11]
  SIE_CAMERA: False
  SIE_COE: 3.0
  JPM: True
  RE_ARRANGE: True
  CATEGORY: ''

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 
  RE_PROB: 0.5 
  PADDING: 10
  PIXEL_MEAN: [0.416, 0.468, 0.355]
  PIXEL_STD: [0.210, 0.206, 0.213]
 
DATASETS:
  NAMES: ('disease_dataset')
  ROOT_DIR: ('/home/yzh_92/Datasets/newClassification/shiyanshizhengli')
  SECOND_DIR: ('')


DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 150
  BASE_LR: 0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 150
  LOG_PERIOD: 300
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4 
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: './logs/disease_classfication/transformer_120.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/diseadse_res'


